import { IDomainList } from "./interfaces";

export const PREFIX_IPADDRESS = ".ipaddress.com";

export const TEMPLATE_HOSTS = `# This file is generated by fetching the ipaddress.com service.
{ content }

# Update time: { updateTime }
# Repo URL: { repoURL }
# Hosts END
`;

export const REGEX_IP = /(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/g;

/**
 * Steam域名列表
 */
export const DomainList: IDomainList = {
    "Steam": [
        "steamcommunity.com",
        "www.steamcommunity.com",
        "store.steampowered.com",
        "api.steampowered.com",
        "steamcdn-a.akamaihd.net",
        "cdn.akamai.steamstatic.com",
        "steam-chat.com"
    ]
}
